### ISSUE TITLE
mypy failing on main branch

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-ml#297]
After upgrading torch to 2.6.0, I see the following mypy test failures on `main`

```pytb
$ make typecheck
mypy cellarium tests
cellarium/ml/layers/head.py:48: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/head.py:51: error: Argument 1 to "zeros_" has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/embedding.py:46: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/embedding.py:89: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/models/onepass_mean_var_std.py:128: error: Unsupported operand types for + ("Tensor" and "None")  [operator]
cellarium/ml/models/onepass_mean_var_std.py:128: note: Right operand is of type "Tensor | None"
```
