### PR TITLE
Fix recent mypy errors

### LINKED ISSUE #297: mypy failing on main branch
After upgrading torch to 2.6.0, I see the following mypy test failures on `main`

```pytb
$ make typecheck
mypy cellarium tests
cellarium/ml/layers/head.py:48: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/head.py:51: error: Argument 1 to "zeros_" has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/embedding.py:46: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/layers/embedding.py:89: error: Argument 1 has incompatible type "Tensor | Module"; expected "Tensor"  [arg-type]
cellarium/ml/models/onepass_mean_var_std.py:128: error: Unsupported operand types for + ("Tensor" and "None")  [operator]
cellarium/ml/models/onepass_mean_var_std.py:128: note: Right operand is of type "Tensor | None"
```

### PR DESCRIPTION
**Pull request by sjfleming**
Closes #297

### CODE REVIEW

**Review by ordabayevy — APPROVED** [review]
Looks great. Just made a small adjustment.
